Back-end setup
CS222-UIUC/collagify pull request #6
Opened 2022-09-23 21:48 UTC by quinnouyang

Spotify API examples, refreshed `.gitgnore`.

2022-09-29 22:55 UTC, jasyip approved these changes

2022-09-29 22:55 UTC, jasyip commented on .github/workflows/jest-test.yml
> +    runs-on: ubuntu-latest
consider other OS? copy my usage of GitHub Actions matrix

2022-09-30 19:06 UTC, quinnouyang commented on .github/workflows/jest-test.yml
> +    runs-on: ubuntu-latest
As long as it's consistent and works for deployment, fine by me. None of our local machines replicate this exactly but we could containerize.

2022-09-30 19:07 UTC, quinnouyang commented
@prathyushreddylpr Could you look through this? Sorry for the mess:)

2022-10-08 01:32 UTC, Heaper327 requested changes
Everything looks good, but we should remove dependency directories like node_modules before merging

2022-10-08 01:34 UTC, quinnouyang commented
Definitely, I've tried resetting the git cache after adding those to `.gitignore`. Might have to manually remove these for now

2022-10-08 01:45 UTC, Heaper327 commented
I have already removed the dependency files on remote, and resetting the git cache fixed my local staging area:
```
git rm -r --cached .
git add .
```
Could you take a look at the files again? I think this branch has done what it needed to do and could be merged now.

2022-10-08 02:35 UTC, Heaper327 approved these changes

2022-10-15 04:33 UTC, merged